# Generated by Django 4.0 on 2022-01-02 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_teacher_pic'),
        ('student', '0006_student_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscripe',
            fields=[
                ('postteacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='teacher.postteacher')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.groupe')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
