# Generated by Django 4.0 on 2022-01-02 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_subscripe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscripe',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
