# Generated by Django 4.0 on 2022-01-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_subscripe_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscripe',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
