# Generated by Django 4.0 on 2022-01-02 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_subscripe_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscripe',
        ),
    ]
