# Generated by Django 4.0 on 2022-01-02 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_teacher_pic'),
        ('student', '0009_subscripe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscripe',
            name='postteacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='teacher.postteacher'),
        ),
    ]
