# Generated by Django 4.0 on 2022-01-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_subscripeteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscripeteacher',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
