# Generated by Django 4.0 on 2022-01-02 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_subscripeteacher_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscripeteacher',
            name='id',
        ),
        migrations.AlterField(
            model_name='subscripeteacher',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='student.student'),
        ),
    ]
